### ISSUE TITLE
mileage entity

### ISSUE THREAD

**Issue by alexanderznamensky** [turbulator/pandora-cas#6]
Добрый день!
Отличный аддон! Спасибо!
У меня только один нюанс - показания спидометра отличаются на 2000 км. Кстати, откуда этот параметр берется, я его не нашел ни в приложении, ни на сайте?

**Comment by turbulator** [comment]
Добрый!
Параметр доступен в API. У меня тоже сильно отличается. Вероятно, он начинает тикать с момента, когда сигналка установлена. Этот параметр считается по GPS и не точно отражает реальный пробег. В новой проге Пандоры этот параметр есть:

![1602122575288](https://user-images.githubusercontent.com/11550042/95421331-74c0b580-0967-11eb-9d1f-23fb67dbf373.jpg)

Кроме этого параметра есть еще mileage_can. Судя по названию должен читаться прям из приборки машины. Но только если это поддерживается сигналкой. Можно запилить.

**Comment by turbulator** [comment]
Проверить mileage_can можно так: в configuration.yaml добавить
```
logger:
  default: warning
  logs:
    custom_components.pandora_cas: info
    custom_components.pandora_cas.api: debug
```
перезагрузить ha и посмотреть Настройки->Журнал сервера->Показать весь журнал. 
Там поискать что-то вроде `... "mileage":"29814.874005530175","mileage_CAN":0 ...`

**Comment by alexanderznamensky** [comment]
Алексей, спасибо! Попробую на досуге!

Приложение не нашел новое - на плей маркете версия от 28 июля 2020 г.
https://play.google.com/store/apps/details?id=ru.alarmtrade.pandora.
На сайте тоже не нашел:
https://alarmtrade.ru/functions/mobilnoe-prilozhenie/.

Может быть зависит от версии сигнализации? У меня Pandora X-1911BT

**Comment by turbulator** [comment]
Так вот же оно: https://play.google.com/store/apps/details?id=ru.alarmtrade.connect

**Comment by alexanderznamensky** [comment]
хм... а я всю жизнь на Pandora OnLine.... )))) век живи, век учись )))
установил новое приложение. пробег появился (тот же, что и в вашем аддоне) 
в логе у меня mileage":"27715.09178572551","mileage_CAN":0 - наверное не считывается значение из can-шины машины

**Comment by turbulator** [comment]
Ага

**Comment by beliy1985** [comment]
>     custom_components.pandora_cas: info
>     custom_components.pandora_cas.api: debug

Сделал, прошивка последняя, вот что дает:
"mileage_CAN":55658, все работает, просто надо сигу обновить, ну и я так понял это зависит от модели тачки, на каких-то поддерживается, на каких-то нет)

**Comment by turbulator** [comment]
А совпадает с пробегом на приборке?

**Comment by beliy1985** [comment]
> А совпадает с пробегом на приборке?

Да, это же из кана данные)

**Comment by turbulator** [comment]
Хочу добавить окно редактирования опций интеграции. А там сделать
выпадашку откуда брать данные: gps или can. А сенсор оставить один.
И потом на этой же базе сделать выбор топлива в процентах или в литрах.

**Comment by beliy1985** [comment]
> Хочу добавить окно редактирования опций интеграции. А там сделать
> 
> выпадашку откуда брать данные: gps или can. А сенсор оставить один.
> 
> И потом на этой же базе сделать выбор топлива в процентах или в литрах.

Отлично, будет как в приложении)

**Comment by alexanderznamensky** [comment]
Алексей, добрый день!

А сложно будет добавить корректировку спидометра, если данные пробега считаются по GPS?
Чтобы не городить template?

```
  - platform: template
    sensors:
      ID_mileage_1:
        friendly_name: "Пробег"
        entity_id: sensor.ID_mileage
        unit_of_measurement: 'км'
        value_template: "{{ (states('sensor.ID_mileage')|float + 1335)|round(0) }}"
        icon_template: mdi:map-marker-distance
```
Интересно еще узнать, как считывать данные пробега из can-шины. У меня авто достаточно свежий (2019), а вот какая версия сигнализации, не знаю (может быть, как посоветовал beliy1985, достаточно обновить прошивку сигнализации).
